### ISSUE TITLE
Watch mode does not recover after error

### ISSUE THREAD

**Issue by dgrammlich** [synyx/buchungsstreber#82]
I use Buchungsstreber 2.8.0 with YAML format.

I started Buchungsstreber in watch mode. After that I startet it in a second terminal in edit mode. It is configured to use `ncalcli` and resolve the incoming dates via regex to template identifiers. If one of the dates has no resolver or identifier, this error occurs:

`NoMethodError: undefined method 'valid_activity?' for nil:NilClass`

It seems that the lines with error messages move the other content up and out of the window.

![buchungsstreber-watch-1](https://user-images.githubusercontent.com/5312377/153826216-806b1ee0-1824-4183-b904-dca7d0aab8a3.png)

In edit mode I remove the conflicting date and save the file. The watch mode still shows the error, even after I press ENTER to reload it manually.

![buchungsstreber-watch-2](https://user-images.githubusercontent.com/5312377/153826526-633e4ef6-6939-436e-be57-bd912b4527f8.png)

Starting the watch mode with a valid file seems fine.

**Comment by dgrammlich** [comment]
Maybe seems to be related to resolvers or generators? Since an uncomplete entry

```yaml
  - 0.5  # TODO
```

 looks like this

![buchungsstreber-watch-3](https://user-images.githubusercontent.com/5312377/153850856-87ed2e74-8da7-4a0b-8a4f-1fffaa404874.png)

**Comment by BuJo** [comment]
Bitte einmal vollstaendigen stacktrace via:

```
buchungsstreber watch --long --debug ....... 2>foo.err
```

**Comment by dgrammlich** [comment]
```shell
NoMethodError: undefined method `valid_activity?' for nil:NilClass
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber/validator.rb:28:in `validate'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber.rb:68:in `block (2 levels) in entries'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber.rb:119:in `fake_stderr'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber.rb:67:in `block in entries'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber.rb:64:in `each'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber.rb:64:in `entries'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber/cli/tui.rb:106:in `redraw'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber/cli/tui.rb:301:in `on_input'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber/cli/tui.rb:73:in `start'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber/cli/app.rb:202:in `watch'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/lib/buchungsstreber/cli/runner.rb:20:in `execute!'
  /.../.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/buchungsstreber-2.8.1/bin/buchungsstreber:19:in `<top (required)>'
  /.../.rbenv/versions/2.5.8/bin/buchungsstreber:23:in `load'
  /.../.rbenv/versions/2.5.8/bin/buchungsstreber:23:in `<main>'
  ...
```
